CREATE INDEX organizations_status_idx ON organizations(status);
CREATE INDEX organization_members_user_idx ON organization_members(user_id, status);
CREATE INDEX agents_status_updated_idx ON agents(organization_id, status, updated_at DESC);
CREATE INDEX agent_versions_version_idx ON agent_versions(agent_id, version_no DESC);
CREATE UNIQUE INDEX agent_versions_one_published_idx ON agent_versions(agent_id) WHERE lifecycle_status = 'published';
CREATE UNIQUE INDEX hosts_tailscale_node_uk ON hosts(organization_id, tailscale_node_id) WHERE tailscale_node_id IS NOT NULL;
CREATE INDEX hosts_status_seen_idx ON hosts(organization_id, status, last_seen_at);
CREATE INDEX host_credentials_active_idx ON host_credentials(host_id, status);
CREATE INDEX host_runtime_capabilities_status_idx ON host_runtime_capabilities(host_id, status);
CREATE INDEX workspaces_host_status_idx ON workspaces(host_id, status);
CREATE UNIQUE INDEX workspace_acl_user_uk ON workspace_acl(workspace_id, user_id) WHERE user_id IS NOT NULL;
CREATE UNIQUE INDEX workspace_acl_team_uk ON workspace_acl(workspace_id, team_id) WHERE team_id IS NOT NULL;
CREATE INDEX boxes_org_status_activity_idx ON boxes(organization_id, status, last_activity_at DESC);
CREATE INDEX boxes_host_status_idx ON boxes(host_id, status);
CREATE INDEX boxes_owner_idx ON boxes(owner_user_id, updated_at DESC);
CREATE UNIQUE INDEX box_acl_user_uk ON box_acl(box_id, user_id) WHERE user_id IS NOT NULL;
CREATE UNIQUE INDEX box_acl_team_uk ON box_acl(box_id, team_id) WHERE team_id IS NOT NULL;
CREATE UNIQUE INDEX runtime_instances_one_active_per_box ON runtime_instances(box_id) WHERE status IN ('starting', 'ready', 'busy', 'stopping');
CREATE INDEX runtime_instances_host_status_idx ON runtime_instances(host_id, status);
CREATE UNIQUE INDEX runs_one_active_per_box ON runs(box_id) WHERE status IN ('dispatching', 'running', 'waiting_approval', 'interrupting', 'disconnected');
CREATE INDEX runs_box_created_idx ON runs(box_id, queued_at DESC);
CREATE INDEX runs_queue_idx ON runs(status, priority, queued_at) WHERE status = 'queued';
CREATE UNIQUE INDEX messages_idempotency_uk ON messages(box_id, idempotency_key) WHERE idempotency_key IS NOT NULL;
CREATE INDEX messages_box_seq_idx ON messages(box_id, box_seq);
CREATE INDEX messages_queue_idx ON messages(box_id, status, box_seq) WHERE status = 'queued';
CREATE INDEX host_commands_dispatch_idx ON host_commands(host_id, status, available_at) WHERE status IN ('pending', 'leased');
CREATE INDEX host_commands_lease_idx ON host_commands(lease_until) WHERE status = 'leased';
CREATE INDEX host_commands_run_idx ON host_commands(run_id, created_at) WHERE run_id IS NOT NULL;
CREATE UNIQUE INDEX box_events_daemon_dedupe_uk ON box_events(host_id, daemon_event_id) WHERE daemon_event_id IS NOT NULL;
CREATE INDEX box_events_run_seq_idx ON box_events(run_id, seq) WHERE run_id IS NOT NULL;
CREATE INDEX box_events_type_time_idx ON box_events(event_type, ingested_at);
CREATE INDEX approvals_pending_idx ON approvals(organization_id, expires_at) WHERE status = 'pending';
CREATE INDEX subagent_instances_run_status_idx ON subagent_instances(run_id, status);
CREATE INDEX todo_items_box_status_idx ON todo_items(box_id, status, position);
CREATE INDEX artifacts_box_created_idx ON artifacts(box_id, created_at DESC);
CREATE INDEX schedules_due_idx ON schedules(next_run_at) WHERE status = 'active';
CREATE INDEX audit_logs_resource_idx ON audit_logs(organization_id, resource_type, resource_id, occurred_at DESC);
CREATE INDEX audit_logs_actor_idx ON audit_logs(organization_id, actor_user_id, occurred_at DESC) WHERE actor_user_id IS NOT NULL;
